services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: sa
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

